### ISSUE TITLE
Command 'Goto link of current line' resulted in an error (Running the contributed command: 'goto-line-link.gotoGithubLine' failed.)

### ISSUE THREAD

**Issue by samuela** [drshrey/goto-line-link#1]
I just tried "Goto link of current file" and got an error. In "Logs (Remote Extension Host)" I found the following traceback:
```
[2021-01-25 22:57:52.826] [exthost] [error] TypeError: Cannot read property 'url' of undefined
	at getRepoInfo (/home/skainswo/.vscode-server/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:84:45)
	at getCurrentFile (/home/skainswo/.vscode-server/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:17:26)
	at getGithubLink (/home/skainswo/.vscode-server/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:93:26)
	at /home/skainswo/.vscode-server/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:117:28
	at _executeContributedCommand (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:725:220)
	at _.$executeContributedCommand (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:725:595)
	at m._doInvokeHandler (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:926)
	at m._invokeHandler (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:916:618)
	at m._receiveRequest (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:915:252)
	at m._receiveOneMessage (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:914:6)
	at /home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:912:136
	at l.fire (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at /home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1118:104
	at l.fire (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at v.fire (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:238:1004)
	at /home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:235:927
	at l.fire (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:46:801)
	at p.acceptChunk (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:231:195)
	at /home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:230:547
	at Socket.t (/home/skainswo/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:240:822)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:186:23) goto-line-link.gotoGithubLine
```

I'm running VSCode using Remote SSH.

**Comment by samuela** [comment]
Just got this error again, but this time with a different error message:
```
[2021-06-10 14:10:40.781] [exthost] [error] Error: ENOENT: no such file or directory, open '.git/config'
	at Object.openSync (fs.js:476:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
	at Object.readFileSync (fs.js:377:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8643)
	at getCurrentFile (/Users/skainswo/.vscode/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:14:37)
	at getGithubLink (/Users/skainswo/.vscode/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:93:26)
	at /Users/skainswo/.vscode/extensions/colo-labs.goto-line-link-1.0.1/out/extension.js:117:28
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:108094)
	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:108532)
	at h._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12797)
	at h._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12489)
	at h._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11145)
	at h._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9945)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8049
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15632)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29788
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15632)
	at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20890)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17776
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at c.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12993)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12341
	at Socket.b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13267)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) goto-line-link.gotoGithubLine
```
I was trying to call goto-line on a file in the Julia package cache `~/.julia/packages/`.
